image: gradle:4.8.1-jdk8

stages:
  - build
  - test

variables:
  GRADLE_USER_HOME: "${CI_PROJECT_DIR}/.gradle"

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches


build:
  stage: build
  script:
    - gradle build
  artifacts:
    paths:
      - build/libs/*.jar
  only:
    - main


test:
  stage: test
  script:
    - gradle jacocoTestReport
