image: gradle:7.4.2-jdk:jdk8

stages:
  - build
  - test


before_script:
  - set GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - gradle build

test:
  stage: test
  script:
    - gradle test

