image: gradle-jdk:jdk8

stages:
  - build
  - test

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - gradle assemble

test:
  stage: test
  script:
    - gradle check

after_script:
  - echo "End CI"